# Generated by Django 4.0.3 on 2022-03-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqtp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '开发中'), (1, '维护中'), (2, '稳定运行')], default=2, verbose_name='项目状态'),
        ),
    ]
