# Generated by Django 4.0.3 on 2022-03-27 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqtp', '0004_config_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id', '-create_time'], 'verbose_name': '项目表'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(null=True, related_name='project_members', to=settings.AUTH_USER_MODEL, verbose_name='普通成员'),
        ),
    ]
